name: release

on:
  workflow_run:
    workflows: [ "continuous integration" ]
    branches: [ master ]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    # https://stackoverflow.com/questions/67516571/github-action-triggered-by-success-of-a-different-action
    # https://github.com/orgs/community/discussions/26238
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        node-version: [ 20.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          npm install
          npm install -g typescript
          npm install -g ts-node

      - name: Build package
        run: npm run build

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
